// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const teamsContainer: string;
export const team: string;
export const dateContainer: string;
