// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const scrollContainer: string;
export const scrollContainerLink: string;
export const scrollContainerItem: string;
